### ISSUE TITLE
profit minus

### ISSUE THREAD

**Issue by yokosta** [ARBProtocol/solana-jupiter-bot#11] opened 2022-08-16 18:09 UTC
How to make it work with a profit? Always sleep page error.  I.e. the bot believes that there will be a profit, but it is not, but the transaction is made anyway. What should I do? How do I speed up?

**Comment by pmioduszewski** [comment] 2022-08-16 20:07
Duplicate of #3

**Closed by pmioduszewski** 2022-08-16 20:07 UTC
